from prisma import Prisma

async def run() -> None:
    client = Prisma()

    await client.connect()

    # ('Beef Patty', 'Protein', 100),
    # ('Bacon', 'Protein', 200),
    # ('Chipotle Black Bean Patty', 'Protein', 400),
    # ('Chicken Breast Patty', 'Protein', 500),
    # ('American Cheese', 'Protein', 300),
    # ('Swiss Cheese', 'Protein', 600),
    # ('Hamburger Bun', 'Carbohydrate', 700),
    # ('Tortilla', 'Carbohydrate', 900),
    # ('Texas Toast', 'Carbohydrate', 1000),
    # ('Chicken Tender', 'Premade', 100),
    # ('Corn Dog', 'Premade', 200),
    # ('Hot Dog', 'Premade', 400),
    # ('French Fries', 'Premade', 300),
    # ('Lettuce', 'Vegetable', 600),
    # ('Tomato', 'Vegetable', 700),
    # ('Pickle', 'Vegetable', 100),
    # ('Onion', 'Vegetable', 900),
    # ('Avacado', 'Vegetable', 200),
    # ('Gig Em Sauce', 'Sauce', 400),
    # ('Ranch', 'Sauce', 200),
    # ('Buffalo', 'Sauce', 300),
    # ('Ketchup', 'Sauce', 1000),
    # ('Ice Cream', 'Dessert', 700),
    # ('Cookie', 'Dessert', 400),
    # ('16 OZ Aquafina', 'Beverage', 800),
    # ('20 OZ Aquafina', 'Beverage', 700),
    # ('Fountain Drink', 'Beverage', 200),
    # ('Cup', 'Non-food', 500),
    # ('Straw', 'Non-food', 300),
    # ('Napkin', 'Non-food', 1000),
    # ('Silverware Bundle', 'Non-food', 200),
    # ('Bag', 'Non-food', 400),
    # ('Basket', 'Non-food', 500),
    # ('Bag', 'Non-food', 400),
    ingredients = [
        {'name': 'Beef Patty', 'category': 'Protein', 'stock': 100},
        {'name': 'Bacon', 'category': 'Protein', 'stock': 200},
        {'name': 'Chipotle Black Bean Patty', 'category': 'Protein', 'stock': 400},
        {'name': 'Chicken Breast Patty', 'category': 'Protein', 'stock': 500},
        {'name': 'American Cheese', 'category': 'Protein', 'stock': 300},
        {'name': 'Swiss Cheese', 'category': 'Protein', 'stock': 600},
        {'name': 'Hamburger Bun', 'category': 'Carbohydrate', 'stock': 700},
        {'name': 'Tortilla', 'category': 'Carbohydrate', 'stock': 900},
        {'name': 'Texas Toast', 'category': 'Carbohydrate', 'stock': 1000},
        {'name': 'Chicken Tender', 'category': 'Premade', 'stock': 100},
        {'name': 'Corn Dog', 'category': 'Premade', 'stock': 200},
        {'name': 'Hot Dog', 'category': 'Premade', 'stock': 400},
        {'name': 'French Fries', 'category': 'Premade', 'stock': 300},
        {'name': 'Lettuce', 'category': 'Vegetable', 'stock': 600},
        {'name': 'Tomato', 'category': 'Vegetable', 'stock': 700},
        {'name': 'Pickle', 'category': 'Vegetable', 'stock': 100},
        {'name': 'Onion', 'category': 'Vegetable', 'stock': 900},
        {'name': 'Avocado', 'category': 'Vegetable', 'stock': 200},
        {'name': 'Gig Em Sauce', 'category': 'Sauce', 'stock': 400},
        {'name': 'Ranch', 'category': 'Sauce', 'stock': 200},
        {'name': 'Buffalo', 'category': 'Sauce', 'stock': 300},
        {'name': 'Ketchup', 'category': 'Sauce', 'stock': 1000},
        {'name': 'Ice Cream', 'category': 'Dessert', 'stock': 700},
        {'name': 'Cookie', 'category': 'Dessert', 'stock': 400},
        {'name': '16 OZ Aquafina', 'category': 'Beverage', 'stock': 800},
        {'name': '20 OZ Aquafina', 'category': 'Beverage', 'stock': 700},
        {'name': 'Fountain Drink', 'category': 'Beverage', 'stock': 200},
        {'name': 'Cup', 'category': 'Non-food', 'stock': 500},
        {'name': 'Straw', 'category': 'Non-food', 'stock': 300},
        {'name': 'Napkin', 'category': 'Non-food', 'stock': 1000},
        {'name': 'Silverware Bundle', 'category': 'Non-food', 'stock': 200},
        {'name': 'Bag', 'category': 'Non-food', 'stock': 400},
        {'name': 'Basket', 'category': 'Non-food', 'stock': 500},
    ]

    for data in ingredients:
        await client.ingredient.create(data=data)

    # ('Bacon Cheeseburger', 'Burgers', 8.29),
    # ('Classic Hamburber', 'Burgers', 6.89),
    # ('Double Stack Burger', 'Burgers', 9.99),
    # ('Gig Em Patty Melt', 'Burgers', 7.59),
    # ('Cheeseburger', 'Burgers', 6.89),
    # ('Black Bean Burger', 'Burgers', 8.38),
    # ('Build your own', 'Burgers', 5.49),
    # ('Revs Grilled Chicken Sandwich', 'Chicken', 8.39),
    # ('Spicy Chicken Sandwich', 'Chicken', 8.39),
    # ('Aggie Chicken Club', 'Chicken', 8.39),
    # ('2 Corn Dog Value Meal', 'Value Meals', 4.99),
    # ('2 Hot Dog Value Meal', 'Value Meals', 4.99),
    # ('3 Tender Entree', 'Value Meals', 4.99),
    # ('3 Chicken Tender Combo', 'Chicken', 7.99),
    # ('French Fries', 'Sides', 1.99),
    # ('Aggie Shakes', 'Dessert', 4.49),
    # ('Cookie Ice Cream Sundae', 'Dessert', 4.69),
    # ('Double Scoop Ice Cream', 'Dessert', 3.29),
    # ('Root Beer Float', 'Dessert', 5.49),
    # ('16 OZ Aquafina', 'Beverages', 1.79),
    # ('20 OZ Aquafine', 'Beverages', 2.19),
    # ('20 OZ Fountain Drink', 'Beverages', 1.99);
    menu_items = [
        {'name': 'Bacon Cheeseburger', 'category': 'Burgers', 'price': 8.29},
        {'name': 'Classic Hamburger', 'category': 'Burgers', 'price': 6.89},
        {'name': 'Double Stack Burger', 'category': 'Burgers', 'price': 9.99},
        {'name': 'Gig Em Patty Melt', 'category': 'Burgers', 'price': 7.59},
        {'name': 'Cheeseburger', 'category': 'Burgers', 'price': 6.89},
        {'name': 'Black Bean Burger', 'category': 'Burgers', 'price': 8.38},
        {'name': 'Build your own', 'category': 'Burgers', 'price': 5.49},
        {'name': 'Revs Grilled Chicken Sandwich', 'category': 'Chicken', 'price': 8.39},
        {'name': 'Spicy Chicken Sandwich', 'category': 'Chicken', 'price': 8.39},
        {'name': 'Aggie Chicken Club', 'category': 'Chicken', 'price': 8.39},
        {'name': '2 Corn Dog Value Meal', 'category': 'Value Meals', 'price': 4.99},
        {'name': '2 Hot Dog Value Meal', 'category': 'Value Meals', 'price': 4.99},
        {'name': '3 Tender Entree', 'category': 'Value Meals', 'price': 4.99},
        {'name': '3 Chicken Tender Combo', 'category': 'Chicken', 'price': 7.99},
        {'name': 'French Fries', 'category': 'Sides', 'price': 1.99},
        {'name': 'Aggie Shakes', 'category': 'Dessert', 'price': 4.49},
        {'name': 'Cookie Ice Cream Sundae', 'category': 'Dessert', 'price': 4.69},
        {'name': 'Double Scoop Ice Cream', 'category': 'Dessert', 'price': 3.29},
        {'name': 'Root Beer Float', 'category': 'Dessert', 'price': 5.49},
        {'name': '16 OZ Aquafina', 'category': 'Beverages', 'price': 1.79},
        {'name': '20 OZ Aquafina', 'category': 'Beverages', 'price': 2.19},
        {'name': '20 OZ Fountain Drink', 'category': 'Beverages', 'price': 1.99},
    ]

    for data in menu_items:
        await client.menu_item.create(data=data)

    await client.disconnect()

if __name__ == '__main__':
    import asyncio
    asyncio.run(run())